name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build (skip tests)
        run: mvn -B -DskipTests package
      - name: Optional smoke run
        run: java -jar target/*-SNAPSHOT.jar
        continue-on-error: true
